USE ElearningDB;

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES;

USE ElearningDB;

DELETE FROM Results;
DELETE FROM Questions;
DELETE FROM Quizzes;
DELETE FROM Lessons;
DELETE FROM Courses;
DELETE FROM Users;

DBCC CHECKIDENT ('Users', RESEED, 0);
DBCC CHECKIDENT ('Courses', RESEED, 0);
DBCC CHECKIDENT ('Lessons', RESEED, 0);
DBCC CHECKIDENT ('Quizzes', RESEED, 0);
DBCC CHECKIDENT ('Questions', RESEED, 0);
DBCC CHECKIDENT ('Results', RESEED, 0);